# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificarProducto.ui'
#
# Created: Wed Sep 24 13:59:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnModificarProducto(object):
    def setupUi(self, vtnModificarProducto):
        vtnModificarProducto.setObjectName(_fromUtf8("vtnModificarProducto"))
        vtnModificarProducto.resize(715, 653)
        self.verticalLayout = QtGui.QVBoxLayout(vtnModificarProducto)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(vtnModificarProducto)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(vtnModificarProducto)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(vtnModificarProducto)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(vtnModificarProducto)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 6, 2, 1, 1)
        self.label_5 = QtGui.QLabel(vtnModificarProducto)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_4 = QtGui.QLabel(vtnModificarProducto)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(vtnModificarProducto)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 1, 3, 1, 1)
        self.tableWidget = QtGui.QTableWidget(vtnModificarProducto)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 4)
        self.pushButton_2 = QtGui.QPushButton(vtnModificarProducto)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 6, 3, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(vtnModificarProducto)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 9, 2, 1, 1)
        self.tableWidget_3 = QtGui.QTableWidget(vtnModificarProducto)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(140)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget_3, 7, 0, 1, 4)
        self.pushButton_3 = QtGui.QPushButton(vtnModificarProducto)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 9, 3, 1, 1)
        self.label_7 = QtGui.QLabel(vtnModificarProducto)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 9, 1, 1, 1)
        self.label_3 = QtGui.QLabel(vtnModificarProducto)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label = QtGui.QLabel(vtnModificarProducto)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(vtnModificarProducto)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 1, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(vtnModificarProducto)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 3, 2, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(vtnModificarProducto)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 4, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(vtnModificarProducto)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 2, 1, 2)
        self.tableWidget_2 = QtGui.QTableWidget(vtnModificarProducto)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(140)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget_2, 10, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(vtnModificarProducto)
        QtCore.QMetaObject.connectSlotsByName(vtnModificarProducto)
        vtnModificarProducto.setTabOrder(self.lineEdit, self.pushButton)
        vtnModificarProducto.setTabOrder(self.pushButton, self.tableWidget)
        vtnModificarProducto.setTabOrder(self.tableWidget, self.lineEdit_4)
        vtnModificarProducto.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        vtnModificarProducto.setTabOrder(self.lineEdit_5, self.lineEdit_2)
        vtnModificarProducto.setTabOrder(self.lineEdit_2, self.pushButton_2)
        vtnModificarProducto.setTabOrder(self.pushButton_2, self.tableWidget_3)
        vtnModificarProducto.setTabOrder(self.tableWidget_3, self.lineEdit_3)
        vtnModificarProducto.setTabOrder(self.lineEdit_3, self.pushButton_3)
        vtnModificarProducto.setTabOrder(self.pushButton_3, self.tableWidget_2)
        vtnModificarProducto.setTabOrder(self.tableWidget_2, self.buttonBox)

    def retranslateUi(self, vtnModificarProducto):
        vtnModificarProducto.setWindowTitle(_translate("vtnModificarProducto", "Modificar Producto", None))
        self.label_8.setText(_translate("vtnModificarProducto", "Producto", None))
        self.label_6.setText(_translate("vtnModificarProducto", "Nombre", None))
        self.label_5.setText(_translate("vtnModificarProducto", "Presentación", None))
        self.label_4.setText(_translate("vtnModificarProducto", "Medicamento", None))
        self.pushButton.setText(_translate("vtnModificarProducto", "Buscar", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vtnModificarProducto", "Código de Barra", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vtnModificarProducto", "Medicamento", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vtnModificarProducto", "Presentación", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("vtnModificarProducto", "Importe", None))
        self.pushButton_2.setText(_translate("vtnModificarProducto", "Buscar", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("vtnModificarProducto", "Nombre", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("vtnModificarProducto", "Monodroga", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("vtnModificarProducto", "Cantidad de Monodroga", None))
        self.pushButton_3.setText(_translate("vtnModificarProducto", "Buscar", None))
        self.label_7.setText(_translate("vtnModificarProducto", "Tipo", None))
        self.label_3.setText(_translate("vtnModificarProducto", "Código de Barra", None))
        self.label.setText(_translate("vtnModificarProducto", "Código de Barra", None))
        self.label_2.setText(_translate("vtnModificarProducto", "Importe", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("vtnModificarProducto", "Tipo", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("vtnModificarProducto", "Unidad de Medida", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("vtnModificarProducto", "Cantidad de Fracciones", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    vtnModificarProducto = QtGui.QWidget()
    ui = Ui_vtnModificarProducto()
    ui.setupUi(vtnModificarProducto)
    vtnModificarProducto.show()
    sys.exit(app.exec_())

