# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrarCobroRemito.ui'
#
# Created: Fri Sep 26 11:13:15 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnRegistrarCobroRemito(object):
    def setupUi(self, vtnRegistrarCobroRemito):
        vtnRegistrarCobroRemito.setObjectName(_fromUtf8("vtnRegistrarCobroRemito"))
        vtnRegistrarCobroRemito.resize(640, 580)
        self.verticalLayout = QtGui.QVBoxLayout(vtnRegistrarCobroRemito)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(vtnRegistrarCobroRemito)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 11, 1, 1, 1)
        self.label_2 = QtGui.QLabel(vtnRegistrarCobroRemito)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(vtnRegistrarCobroRemito)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 11, 3, 1, 1)
        self.pushButton = QtGui.QPushButton(vtnRegistrarCobroRemito)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 2, 4, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(vtnRegistrarCobroRemito)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 5, 2, 1, 2)
        self.lineEdit_4 = QtGui.QLineEdit(vtnRegistrarCobroRemito)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 11, 2, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(vtnRegistrarCobroRemito)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 2, 2, 1, 2)
        self.pushButton_3 = QtGui.QPushButton(vtnRegistrarCobroRemito)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 7, 4, 1, 1)
        self.label_4 = QtGui.QLabel(vtnRegistrarCobroRemito)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(vtnRegistrarCobroRemito)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(vtnRegistrarCobroRemito)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 10, 4, 1, 1)
        self.tableWidget_3 = QtGui.QTableWidget(vtnRegistrarCobroRemito)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget_3, 9, 1, 1, 4)
        self.label_5 = QtGui.QLabel(vtnRegistrarCobroRemito)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(vtnRegistrarCobroRemito)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 2, 1, 3)
        self.label_6 = QtGui.QLabel(vtnRegistrarCobroRemito)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(vtnRegistrarCobroRemito)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 5, 4, 1, 1)
        self.label_7 = QtGui.QLabel(vtnRegistrarCobroRemito)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 10, 3, 1, 1)
        self.label = QtGui.QLabel(vtnRegistrarCobroRemito)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tableWidget_2 = QtGui.QTableWidget(vtnRegistrarCobroRemito)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget_2, 6, 1, 1, 4)
        self.tableWidget = QtGui.QTableWidget(vtnRegistrarCobroRemito)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 3, 1, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(vtnRegistrarCobroRemito)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 12, 3, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(vtnRegistrarCobroRemito)
        QtCore.QMetaObject.connectSlotsByName(vtnRegistrarCobroRemito)
        vtnRegistrarCobroRemito.setTabOrder(self.lineEdit, self.lineEdit_2)
        vtnRegistrarCobroRemito.setTabOrder(self.lineEdit_2, self.pushButton)
        vtnRegistrarCobroRemito.setTabOrder(self.pushButton, self.tableWidget)
        vtnRegistrarCobroRemito.setTabOrder(self.tableWidget, self.lineEdit_3)
        vtnRegistrarCobroRemito.setTabOrder(self.lineEdit_3, self.pushButton_2)
        vtnRegistrarCobroRemito.setTabOrder(self.pushButton_2, self.tableWidget_2)
        vtnRegistrarCobroRemito.setTabOrder(self.tableWidget_2, self.pushButton_3)
        vtnRegistrarCobroRemito.setTabOrder(self.pushButton_3, self.tableWidget_3)
        vtnRegistrarCobroRemito.setTabOrder(self.tableWidget_3, self.lineEdit_4)
        vtnRegistrarCobroRemito.setTabOrder(self.lineEdit_4, self.pushButton_4)
        vtnRegistrarCobroRemito.setTabOrder(self.pushButton_4, self.buttonBox)

    def retranslateUi(self, vtnRegistrarCobroRemito):
        vtnRegistrarCobroRemito.setWindowTitle(_translate("vtnRegistrarCobroRemito", "Registrar Cobro Remito", None))
        self.label_9.setText(_translate("vtnRegistrarCobroRemito", "Efectivo Entrgado", None))
        self.label_2.setText(_translate("vtnRegistrarCobroRemito", "* CUIT", None))
        self.pushButton_4.setText(_translate("vtnRegistrarCobroRemito", "Calcular Vuelto", None))
        self.pushButton.setText(_translate("vtnRegistrarCobroRemito", "Buscar", None))
        self.pushButton_3.setText(_translate("vtnRegistrarCobroRemito", "Agregar", None))
        self.label_4.setText(_translate("vtnRegistrarCobroRemito", "Remito", None))
        self.label_3.setText(_translate("vtnRegistrarCobroRemito", "* Razón Social", None))
        self.label_8.setText(_translate("vtnRegistrarCobroRemito", "$0.00", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("vtnRegistrarCobroRemito", "Código", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("vtnRegistrarCobroRemito", "Cantidad", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("vtnRegistrarCobroRemito", "Importe", None))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("vtnRegistrarCobroRemito", "Descuento OS", None))
        self.label_5.setText(_translate("vtnRegistrarCobroRemito", "Número", None))
        self.label_6.setText(_translate("vtnRegistrarCobroRemito", "Factura", None))
        self.pushButton_2.setText(_translate("vtnRegistrarCobroRemito", "Buscar", None))
        self.label_7.setText(_translate("vtnRegistrarCobroRemito", "Importe Total:", None))
        self.label.setText(_translate("vtnRegistrarCobroRemito", "Obra Social", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("vtnRegistrarCobroRemito", "Código", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("vtnRegistrarCobroRemito", "Cantidad", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("vtnRegistrarCobroRemito", "Importe", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vtnRegistrarCobroRemito", "Razón Social", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vtnRegistrarCobroRemito", "CUIT", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vtnRegistrarCobroRemito", "Dirección", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    vtnRegistrarCobroRemito = QtGui.QWidget()
    ui = Ui_vtnRegistrarCobroRemito()
    ui.setupUi(vtnRegistrarCobroRemito)
    vtnRegistrarCobroRemito.show()
    sys.exit(app.exec_())

