# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventaConRemito.ui'
#
# Created: Fri Sep 26 11:13:15 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnVentaConRemito(object):
    def setupUi(self, vtnVentaConRemito):
        vtnVentaConRemito.setObjectName(_fromUtf8("vtnVentaConRemito"))
        vtnVentaConRemito.resize(764, 613)
        self.verticalLayout = QtGui.QVBoxLayout(vtnVentaConRemito)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(vtnVentaConRemito)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(vtnVentaConRemito)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_2.addWidget(self.pushButton_5, 11, 4, 1, 1)
        self.label_6 = QtGui.QLabel(vtnVentaConRemito)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(vtnVentaConRemito)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 12, 0, 1, 1)
        self.tableWidget_2 = QtGui.QTableWidget(vtnVentaConRemito)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidget_2, 10, 1, 1, 5)
        self.pushButton_4 = QtGui.QPushButton(vtnVentaConRemito)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 8, 5, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(vtnVentaConRemito)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_2.addWidget(self.lineEdit_3, 6, 3, 1, 2)
        self.tableWidget = QtGui.QTableWidget(vtnVentaConRemito)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 3, 1, 1, 5)
        self.label_9 = QtGui.QLabel(vtnVentaConRemito)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 6, 2, 1, 1)
        self.label_10 = QtGui.QLabel(vtnVentaConRemito)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 8, 2, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(vtnVentaConRemito)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_2.addWidget(self.lineEdit_5, 11, 3, 1, 1)
        self.label_5 = QtGui.QLabel(vtnVentaConRemito)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 7, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(vtnVentaConRemito)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 14, 4, 1, 2)
        self.label_2 = QtGui.QLabel(vtnVentaConRemito)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(vtnVentaConRemito)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 4, 1, 1)
        self.tableWidget_3 = QtGui.QTableWidget(vtnVentaConRemito)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidget_3, 13, 1, 1, 5)
        self.lineEdit_2 = QtGui.QLineEdit(vtnVentaConRemito)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 2, 1, 2)
        self.lineEdit = QtGui.QLineEdit(vtnVentaConRemito)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 1, 2, 1, 3)
        self.lineEdit_4 = QtGui.QLineEdit(vtnVentaConRemito)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_2.addWidget(self.lineEdit_4, 8, 3, 1, 2)
        self.label_3 = QtGui.QLabel(vtnVentaConRemito)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(vtnVentaConRemito)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(vtnVentaConRemito)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 11, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(vtnVentaConRemito)
        QtCore.QMetaObject.connectSlotsByName(vtnVentaConRemito)
        vtnVentaConRemito.setTabOrder(self.lineEdit, self.lineEdit_2)
        vtnVentaConRemito.setTabOrder(self.lineEdit_2, self.pushButton_2)
        vtnVentaConRemito.setTabOrder(self.pushButton_2, self.tableWidget)
        vtnVentaConRemito.setTabOrder(self.tableWidget, self.lineEdit_3)
        vtnVentaConRemito.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        vtnVentaConRemito.setTabOrder(self.lineEdit_4, self.pushButton_4)
        vtnVentaConRemito.setTabOrder(self.pushButton_4, self.tableWidget_2)
        vtnVentaConRemito.setTabOrder(self.tableWidget_2, self.lineEdit_5)
        vtnVentaConRemito.setTabOrder(self.lineEdit_5, self.pushButton_5)
        vtnVentaConRemito.setTabOrder(self.pushButton_5, self.tableWidget_3)
        vtnVentaConRemito.setTabOrder(self.tableWidget_3, self.buttonBox)

    def retranslateUi(self, vtnVentaConRemito):
        vtnVentaConRemito.setWindowTitle(_translate("vtnVentaConRemito", "Venta con Remito", None))
        self.label.setText(_translate("vtnVentaConRemito", "Nombre y Apellido", None))
        self.pushButton_5.setText(_translate("vtnVentaConRemito", "Agregar", None))
        self.label_6.setText(_translate("vtnVentaConRemito", "Producto", None))
        self.label_8.setText(_translate("vtnVentaConRemito", "Remito", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("vtnVentaConRemito", "Código de Barra", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("vtnVentaConRemito", "Medicamento", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("vtnVentaConRemito", "Presentación", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("vtnVentaConRemito", "Monodroga", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("vtnVentaConRemito", "Importe", None))
        self.pushButton_4.setText(_translate("vtnVentaConRemito", "Buscar", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vtnVentaConRemito", "NyA", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vtnVentaConRemito", "DNI", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vtnVentaConRemito", "Dirección", None))
        self.label_9.setText(_translate("vtnVentaConRemito", "Nombre", None))
        self.label_10.setText(_translate("vtnVentaConRemito", "Nombre", None))
        self.label_5.setText(_translate("vtnVentaConRemito", "Monodroga", None))
        self.label_2.setText(_translate("vtnVentaConRemito", "DNI", None))
        self.pushButton_2.setText(_translate("vtnVentaConRemito", "Buscar", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("vtnVentaConRemito", "Código de Barra", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("vtnVentaConRemito", "Cantidad", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("vtnVentaConRemito", "Importe", None))
        self.label_3.setText(_translate("vtnVentaConRemito", "Cliente", None))
        self.label_4.setText(_translate("vtnVentaConRemito", "Medicamento", None))
        self.label_7.setText(_translate("vtnVentaConRemito", "Cantidad", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    vtnVentaConRemito = QtGui.QWidget()
    ui = Ui_vtnVentaConRemito()
    ui.setupUi(vtnVentaConRemito)
    vtnVentaConRemito.show()
    sys.exit(app.exec_())

