cd ~/Documentos/FarmaciaCrisol/Desarrollo/ventanas
pyuic4 -x vtnAltaCliente.ui -o vtnAltaCliente.py
pyuic4 -x vtnAjusteNegativoStock.ui -o vtnAjusteNegativoStock.py
pyuic4 -x vtnAltaMedicamento.ui -o vtnAltaMedicamento.py
pyuic4 -x vtnAltaMonodroga.ui -o vtnAltaMonodroga.py
pyuic4 -x vtnAltaPresentacion.ui -o vtnAltaPresentacion.py
pyuic4 -x vtnAltaProducto.ui -o vtnAltaProducto.py
pyuic4 -x vtnBajaCliente.ui -o vtnBajaCliente.py
pyuic4 -x vtnAltaLote.ui -o vtnAltaLote.py
pyuic4 -x vtnBajaLote.ui -o vtnBajaLote.py
pyuic4 -x vtnBajaRemito.ui -o vtnBajaRemito.py
pyuic4 -x vtnBajaPresentacion.ui -o vtnBajaPresentacion.py
pyuic4 -x vtnBajaProducto.ui -o vtnBajaProducto.py
pyuic4 -x vtnBajaMedicamento.ui -o vtnBajaMedicamento.py
pyuic4 -x vtnBajaMonodroga.ui -o vtnBajaMonodroga.py
pyuic4 -x vtnDevolucionDeCliente.ui -o vtnDevolucionDeCliente.py
pyuic4 -x vtnFraccionarProducto.ui -o vtnFraccionarProducto.py
pyuic4 -x vtnIngresar.ui -o vtnIngresar.py
pyuic4 -x vtnListar.ui -o vtnListar.py
pyuic4 -x vtnModificarCliente.ui -o vtnModificarCliente.py
pyuic4 -x vtnModificarLote.ui -o vtnModificarLote.py
pyuic4 -x vtnModificarMedicamento.ui -o vtnModificarMedicamento.py
pyuic4 -x vtnModificarMonodroga.ui -o vtnModificarMonodroga.py
pyuic4 -x vtnModificarProducto.ui -o vtnModificarProducto.py
pyuic4 -x vtnModificarPresentacion.ui -o vtnModificarPresentacion.py
pyuic4 -x vtnModificarRemito.ui -o vtnModificarRemito.py
pyuic4 -x vtnRegistrarCobroRemito.ui -o vtnRegistrarCobroRemito.py
pyuic4 -x vtnReintegroCliente.ui -o vtnReintegroCliente.py
pyuic4 -x vtnVentanaPrincipal.ui -o vtnVentanaPrincipal.py
pyuic4 -x vtnVentaContado.ui -o vtnVentaContado.py
pyuic4 -x vtnVentaConRemito.ui -o vtnVentaConRemito.py

