# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtnRegistrarCobroRemito.ui'
#
# Created: Tue Oct 28 16:56:01 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnRegistrarCobroRemito(object):
    def setupUi(self, vtnRegistrarCobroRemito):
        vtnRegistrarCobroRemito.setObjectName(_fromUtf8("vtnRegistrarCobroRemito"))
        vtnRegistrarCobroRemito.resize(640, 632)
        self.verticalLayout = QtGui.QVBoxLayout(vtnRegistrarCobroRemito)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbObraSocial = QtGui.QGroupBox(vtnRegistrarCobroRemito)
        self.gbObraSocial.setObjectName(_fromUtf8("gbObraSocial"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbObraSocial)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit = QtGui.QLineEdit(self.gbObraSocial)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gbObraSocial)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.gbObraSocial)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gbObraSocial)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.gbObraSocial)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.gbObraSocial)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.gbObraSocial)
        self.gbRemito = QtGui.QGroupBox(vtnRegistrarCobroRemito)
        self.gbRemito.setObjectName(_fromUtf8("gbRemito"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbRemito)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.gbRemito)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gbRemito)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gbRemito)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.tableWidget_2 = QtGui.QTableWidget(self.gbRemito)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.tableWidget_2, 1, 0, 1, 3)
        self.pushButton_3 = QtGui.QPushButton(self.gbRemito)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.gbRemito)
        self.gbFactura = QtGui.QGroupBox(vtnRegistrarCobroRemito)
        self.gbFactura.setObjectName(_fromUtf8("gbFactura"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbFactura)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_9 = QtGui.QLabel(self.gbFactura)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.gbFactura)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 2, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.gbFactura)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 4, 1, 1)
        self.tableWidget_3 = QtGui.QTableWidget(self.gbFactura)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tableWidget_3, 0, 0, 1, 5)
        self.label_7 = QtGui.QLabel(self.gbFactura)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 3, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.gbFactura)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_4.addWidget(self.lineEdit_4, 2, 2, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.gbFactura)
        self.buttonBox = QtGui.QDialogButtonBox(vtnRegistrarCobroRemito)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(vtnRegistrarCobroRemito)
        QtCore.QMetaObject.connectSlotsByName(vtnRegistrarCobroRemito)

    def retranslateUi(self, vtnRegistrarCobroRemito):
        vtnRegistrarCobroRemito.setWindowTitle(_translate("vtnRegistrarCobroRemito", "Registrar Cobro Remito", None))
        self.gbObraSocial.setTitle(_translate("vtnRegistrarCobroRemito", "Obra Social", None))
        self.pushButton.setText(_translate("vtnRegistrarCobroRemito", "Buscar", None))
        self.label_2.setText(_translate("vtnRegistrarCobroRemito", "* CUIT", None))
        self.label_3.setText(_translate("vtnRegistrarCobroRemito", "* Razón Social", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vtnRegistrarCobroRemito", "Razón Social", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vtnRegistrarCobroRemito", "CUIT", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vtnRegistrarCobroRemito", "Dirección", None))
        self.gbRemito.setTitle(_translate("vtnRegistrarCobroRemito", "Remito", None))
        self.label_5.setText(_translate("vtnRegistrarCobroRemito", "Número", None))
        self.pushButton_2.setText(_translate("vtnRegistrarCobroRemito", "Buscar", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("vtnRegistrarCobroRemito", "Código", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("vtnRegistrarCobroRemito", "Cantidad", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("vtnRegistrarCobroRemito", "Importe", None))
        self.pushButton_3.setText(_translate("vtnRegistrarCobroRemito", "Agregar", None))
        self.gbFactura.setTitle(_translate("vtnRegistrarCobroRemito", "Factura", None))
        self.label_9.setText(_translate("vtnRegistrarCobroRemito", "Efectivo Entrgado", None))
        self.pushButton_4.setText(_translate("vtnRegistrarCobroRemito", "Calcular Vuelto", None))
        self.label_8.setText(_translate("vtnRegistrarCobroRemito", "$0.00", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("vtnRegistrarCobroRemito", "Código", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("vtnRegistrarCobroRemito", "Cantidad", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("vtnRegistrarCobroRemito", "Importe", None))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("vtnRegistrarCobroRemito", "Descuento OS", None))
        self.label_7.setText(_translate("vtnRegistrarCobroRemito", "Importe Total:", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    vtnRegistrarCobroRemito = QtGui.QWidget()
    ui = Ui_vtnRegistrarCobroRemito()
    ui.setupUi(vtnRegistrarCobroRemito)
    vtnRegistrarCobroRemito.show()
    sys.exit(app.exec_())

