# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtnVentaContado.ui'
#
# Created: Tue Oct 28 16:56:01 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnVentaContado(object):
    def setupUi(self, vtnVentaContado):
        vtnVentaContado.setObjectName(_fromUtf8("vtnVentaContado"))
        vtnVentaContado.resize(831, 678)
        self.verticalLayout = QtGui.QVBoxLayout(vtnVentaContado)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbObraSocial = QtGui.QGroupBox(vtnVentaContado)
        self.gbObraSocial.setObjectName(_fromUtf8("gbObraSocial"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbObraSocial)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_2 = QtGui.QPushButton(self.gbObraSocial)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.gbObraSocial)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gbObraSocial)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gbObraSocial)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gbObraSocial)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.gbObraSocial)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.gbObraSocial)
        self.gpProducto = QtGui.QGroupBox(vtnVentaContado)
        self.gpProducto.setObjectName(_fromUtf8("gpProducto"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gpProducto)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.gpProducto)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gpProducto)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.gpProducto)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.pushButton_4, 4, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.pushButton_3 = QtGui.QPushButton(self.gpProducto)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 5, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.lineEdit_5 = QtGui.QLineEdit(self.gpProducto)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_3.addWidget(self.lineEdit_5, 3, 1, 1, 1)
        self.tableWidget_2 = QtGui.QTableWidget(self.gpProducto)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.tableWidget_2, 2, 0, 1, 2)
        self.gbMonodroga = QtGui.QGroupBox(self.gpProducto)
        self.gbMonodroga.setObjectName(_fromUtf8("gbMonodroga"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gbMonodroga)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lineEdit_4 = QtGui.QLineEdit(self.gbMonodroga)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_5.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gbMonodroga)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gbMonodroga)
        self.pushButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_5.addWidget(self.pushButton, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.gridLayout_3.addWidget(self.gbMonodroga, 1, 0, 1, 2)
        self.gbMedicamento = QtGui.QGroupBox(self.gpProducto)
        self.gbMedicamento.setObjectName(_fromUtf8("gbMedicamento"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbMedicamento)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.gbMedicamento)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gbMedicamento)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_4.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout_3.addWidget(self.gbMedicamento, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.gpProducto)
        self.gbFactura = QtGui.QGroupBox(vtnVentaContado)
        self.gbFactura.setObjectName(_fromUtf8("gbFactura"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.gbFactura)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tableWidget_3 = QtGui.QTableWidget(self.gbFactura)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(80)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.verticalHeader().setStretchLastSection(False)
        self.gridLayout_6.addWidget(self.tableWidget_3, 0, 0, 1, 3)
        self.comboBox = QtGui.QComboBox(self.gbFactura)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox, 1, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_10 = QtGui.QLabel(self.gbFactura)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.verticalLayout.addWidget(self.gbFactura)
        self.buttonBox = QtGui.QDialogButtonBox(vtnVentaContado)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(vtnVentaContado)
        QtCore.QMetaObject.connectSlotsByName(vtnVentaContado)

    def retranslateUi(self, vtnVentaContado):
        vtnVentaContado.setWindowTitle(_translate("vtnVentaContado", "Venta Contado", None))
        self.gbObraSocial.setTitle(_translate("vtnVentaContado", "Obra Social", None))
        self.pushButton_2.setText(_translate("vtnVentaContado", "Buscar", None))
        self.label_2.setText(_translate("vtnVentaContado", "* Razón Social", None))
        self.label_3.setText(_translate("vtnVentaContado", "* CUIT", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vtnVentaContado", "Razón Social", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vtnVentaContado", "CUIT", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vtnVentaContado", "Dirección", None))
        self.gpProducto.setTitle(_translate("vtnVentaContado", "Producto", None))
        self.label_7.setText(_translate("vtnVentaContado", "Cantidad", None))
        self.label_8.setText(_translate("vtnVentaContado", "Descuento Obra Social ?", None))
        self.pushButton_4.setText(_translate("vtnVentaContado", "Con Descuento", None))
        self.pushButton_3.setText(_translate("vtnVentaContado", "Sin Descuento", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("vtnVentaContado", "Código de Barra", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("vtnVentaContado", "Medicamento", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("vtnVentaContado", "Presentación", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("vtnVentaContado", "Monodroga", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("vtnVentaContado", "Descuento OS", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("vtnVentaContado", "Importe", None))
        self.gbMonodroga.setTitle(_translate("vtnVentaContado", "Monodroga", None))
        self.label_11.setText(_translate("vtnVentaContado", "Nombre", None))
        self.pushButton.setText(_translate("vtnVentaContado", "Buscar", None))
        self.gbMedicamento.setTitle(_translate("vtnVentaContado", "Medicamento", None))
        self.label_12.setText(_translate("vtnVentaContado", "Nombre Comercial", None))
        self.gbFactura.setTitle(_translate("vtnVentaContado", "Factura", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("vtnVentaContado", "Código de Barra", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("vtnVentaContado", "Cantidad", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("vtnVentaContado", "Importe", None))
        self.comboBox.setItemText(0, _translate("vtnVentaContado", "Tarjeta de Crédito", None))
        self.comboBox.setItemText(1, _translate("vtnVentaContado", "Tarjeta de Débito", None))
        self.comboBox.setItemText(2, _translate("vtnVentaContado", "Efectivo", None))
        self.comboBox.setItemText(3, _translate("vtnVentaContado", "Nota de Crédito", None))
        self.label_10.setText(_translate("vtnVentaContado", "Forma de Pago", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    vtnVentaContado = QtGui.QWidget()
    ui = Ui_vtnVentaContado()
    ui.setupUi(vtnVentaContado)
    vtnVentaContado.show()
    sys.exit(app.exec_())

