# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventaContado.ui'
#
# Created: Fri Oct  3 15:23:13 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnVentaContado(object):
    def setupUi(self, vtnVentaContado):
        vtnVentaContado.setObjectName(_fromUtf8("vtnVentaContado"))
        vtnVentaContado.resize(831, 678)
        self.verticalLayout = QtGui.QVBoxLayout(vtnVentaContado)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(vtnVentaContado)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(vtnVentaContado)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 2, 5, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(vtnVentaContado)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 8, 3, 1, 3)
        self.label_10 = QtGui.QLabel(vtnVentaContado)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 15, 2, 1, 1)
        self.label_8 = QtGui.QLabel(vtnVentaContado)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 11, 2, 1, 1)
        self.label_12 = QtGui.QLabel(vtnVentaContado)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 6, 2, 1, 1)
        self.label_6 = QtGui.QLabel(vtnVentaContado)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 7, 1, 1, 1)
        self.label = QtGui.QLabel(vtnVentaContado)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(vtnVentaContado)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 2, 1, 4)
        self.comboBox = QtGui.QComboBox(vtnVentaContado)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 15, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.lineEdit_5 = QtGui.QLineEdit(vtnVentaContado)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 10, 3, 1, 1)
        self.label_5 = QtGui.QLabel(vtnVentaContado)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.tableWidget_3 = QtGui.QTableWidget(vtnVentaContado)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(80)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget_3, 14, 1, 1, 6)
        self.label_7 = QtGui.QLabel(vtnVentaContado)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 10, 2, 1, 1)
        self.label_3 = QtGui.QLabel(vtnVentaContado)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(vtnVentaContado)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 3, 1, 1, 6)
        self.label_2 = QtGui.QLabel(vtnVentaContado)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(vtnVentaContado)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 6, 3, 1, 3)
        self.label_11 = QtGui.QLabel(vtnVentaContado)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 8, 2, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(vtnVentaContado)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 2, 2, 1, 3)
        self.pushButton = QtGui.QPushButton(vtnVentaContado)
        self.pushButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 8, 6, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(vtnVentaContado)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 12, 4, 1, 1)
        self.tableWidget_2 = QtGui.QTableWidget(vtnVentaContado)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget_2, 9, 1, 1, 6)
        self.buttonBox = QtGui.QDialogButtonBox(vtnVentaContado)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 15, 5, 1, 2)
        self.label_9 = QtGui.QLabel(vtnVentaContado)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 13, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(vtnVentaContado)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 11, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(vtnVentaContado)
        QtCore.QMetaObject.connectSlotsByName(vtnVentaContado)
        vtnVentaContado.setTabOrder(self.lineEdit, self.lineEdit_2)
        vtnVentaContado.setTabOrder(self.lineEdit_2, self.pushButton_2)
        vtnVentaContado.setTabOrder(self.pushButton_2, self.tableWidget)
        vtnVentaContado.setTabOrder(self.tableWidget, self.lineEdit_3)
        vtnVentaContado.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        vtnVentaContado.setTabOrder(self.lineEdit_4, self.pushButton)
        vtnVentaContado.setTabOrder(self.pushButton, self.tableWidget_2)
        vtnVentaContado.setTabOrder(self.tableWidget_2, self.lineEdit_5)
        vtnVentaContado.setTabOrder(self.lineEdit_5, self.pushButton_4)
        vtnVentaContado.setTabOrder(self.pushButton_4, self.pushButton_3)
        vtnVentaContado.setTabOrder(self.pushButton_3, self.tableWidget_3)
        vtnVentaContado.setTabOrder(self.tableWidget_3, self.comboBox)
        vtnVentaContado.setTabOrder(self.comboBox, self.buttonBox)

    def retranslateUi(self, vtnVentaContado):
        vtnVentaContado.setWindowTitle(_translate("vtnVentaContado", "Venta Contado", None))
        self.label_4.setText(_translate("vtnVentaContado", "Producto", None))
        self.pushButton_2.setText(_translate("vtnVentaContado", "Buscar", None))
        self.label_10.setText(_translate("vtnVentaContado", "Forma de Pago", None))
        self.label_8.setText(_translate("vtnVentaContado", "Descuento Obra Social ?", None))
        self.label_12.setText(_translate("vtnVentaContado", "Nombre", None))
        self.label_6.setText(_translate("vtnVentaContado", "Monodroga", None))
        self.label.setText(_translate("vtnVentaContado", "Obra Social", None))
        self.comboBox.setItemText(0, _translate("vtnVentaContado", "Tarjeta de Crédito", None))
        self.comboBox.setItemText(1, _translate("vtnVentaContado", "Tarjeta de Débito", None))
        self.comboBox.setItemText(2, _translate("vtnVentaContado", "Efectivo", None))
        self.comboBox.setItemText(3, _translate("vtnVentaContado", "Nota de Crédito", None))
        self.label_5.setText(_translate("vtnVentaContado", "Medicamento", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("vtnVentaContado", "Código de Barra", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("vtnVentaContado", "Cantidad", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("vtnVentaContado", "Importe", None))
        self.label_7.setText(_translate("vtnVentaContado", "Cantidad", None))
        self.label_3.setText(_translate("vtnVentaContado", "* CUIT", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vtnVentaContado", "Razón Social", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vtnVentaContado", "CUIT", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vtnVentaContado", "Dirección", None))
        self.label_2.setText(_translate("vtnVentaContado", "* Razón Social", None))
        self.label_11.setText(_translate("vtnVentaContado", "Nombre", None))
        self.pushButton.setText(_translate("vtnVentaContado", "Buscar", None))
        self.pushButton_3.setText(_translate("vtnVentaContado", "Sin Descuento", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("vtnVentaContado", "Código de Barra", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("vtnVentaContado", "Medicamento", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("vtnVentaContado", "Presentación", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("vtnVentaContado", "Monodroga", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("vtnVentaContado", "Descuento OS", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("vtnVentaContado", "Importe", None))
        self.label_9.setText(_translate("vtnVentaContado", "Factura", None))
        self.pushButton_4.setText(_translate("vtnVentaContado", "Con Descuento", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    vtnVentaContado = QtGui.QWidget()
    ui = Ui_vtnVentaContado()
    ui.setupUi(vtnVentaContado)
    vtnVentaContado.show()
    sys.exit(app.exec_())

